SELECT tp.ID, tp.POST_TITLE, tu.USER_EMAIL 
FROM TBL_POST tp
JOIN TBL_USER tu
ON tp.USER_ID = tu.ID 
ORDER BY ID DESC;

-- 댓글을 단 사용자
SELECT * FROM TBL_REPLY;
SELECT tr.REPLY_CONTENT, tu.USER_EMAIL
FROM TBL_REPLY tr	
JOIN TBL_USER tu
ON tr.USER_ID = tu.ID
WHERE REPLY_CONTENT LIKE '%한민%';

/*
 * SQL의 실행 순서
 * FROM > JOIN > ON > WHERE > GROUP BY > HAVING > SELECT > ORDER BY
 * */

-- 주문 날짜, 주문자의 이름
-- 주문자 정보 조회
SELECT tor.ORDER_START_DATE, tb.BUYER_NAME
FROM TBL_ORDER tor
JOIN TBL_BUYER tb
ON tor.BUYER_ID = tb.ID;

-- 가장 인기 많은 상품을 구매한 사용자의 정보와 상품 이름을 조회
SELECT * FROM TBL_BUYER;
SELECT * FROM TBL_PRODUCT;
SELECT * FROM TBL_ORDER;

SELECT PRODUCT_ID
FROM TBL_ORDER
GROUP BY PRODUCT_ID
ORDER BY COUNT(PRODUCT_ID) DESC;

-- 가장 많이 구매 한 상품의 아이디

SELECT *
   FROM TBL_ORDER TBO
   WHERE PRODUCT_ID = (
      SELECT PRODUCT_ID
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
      HAVING COUNT(PRODUCT_ID) = (
         SELECT MAX(COUNT(PRODUCT_ID))
         FROM TBL_ORDER
         GROUP BY PRODUCT_ID
      )
   );

SELECT TBU.*, TBP.PRODUCT_NAME
FROM (
   SELECT *
   FROM TBL_ORDER TBO
   WHERE PRODUCT_ID = (
      SELECT PRODUCT_ID
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
      HAVING COUNT(PRODUCT_ID) = (
         SELECT MAX(COUNT(PRODUCT_ID))
         FROM TBL_ORDER
         GROUP BY PRODUCT_ID
      )
   )
) TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT *
FROM (
	SELECT PRODUCT_ID
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
	ORDER BY COUNT(PRODUCT_ID) DESC
)
WHERE ROWNUM <= 1;

-- 인기 상품을 구매한 구매자 아이디
SELECT *
FROM TBL_ORDER
WHERE PRODUCT_ID = 3;

-- 인기 상품을 구매한 구매자 정보
SELECT *
FROM TBL_BUYER
WHERE ID IN(
	SELECT BUYER_ID
	FROM TBL_ORDER
	WHERE PRODUCT_ID = 3
);

SELECT PRODUCT_ID
FROM (
	SELECT PRODUCT_ID, COUNT(PRODUCT_ID) AS "상품 판매 수"
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
	ORDER BY COUNT(PRODUCT_ID) DESC
)
WHERE ROWNUM <= 1;

SELECT ID
FROM TBL_BUYER
WHERE ID IN(
	SELECT BUYER_ID
	FROM TBL_ORDER
	WHERE PRODUCT_ID = 3
);


-- 가장 인기 많음 상품을 구매한
-- 사용자의 정보와 상품 이름을 조회
SELECT *
FROM TBL_ORDER tor
JOIN TBL_BUYER tb
ON tor.BUYER_ID = tb.ID
JOIN TBL_PRODUCT tp
ON tor.BUYER_ID = tp.ID
WHERE PRODUCT_ID = (
	SELECT PRODUCT_ID
  	 FROM TBL_ORDER
  	 GROUP BY PRODUCT_ID
  	 HAVING COUNT(PRODUCT_ID) = (
      SELECT MAX(COUNT(PRODUCT_ID))
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
	)
);


-- 상품 이름과 총 판매 매출 조회
SELECT PRODUCT_NAME AS "상품이름", PRODUCT_PRICE || '원' AS "상품가격", COUNT(PRODUCT_ID)||'개' AS "판매 수량", PRODUCT_PRICE * COUNT(PRODUCT_ID) || '원' AS "총 매출"
FROM TBL_PRODUCT TBP
JOIN TBL_ORDER	TBO
ON TBP.ID = TBO.PRODUCT_ID
GROUP BY PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_ID;

SELECT PRODUCT_ID, COUNT(PRODUCT_ID)
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY PRODUCT_ID;

-- 상품을 구매한 20 ~ 30대 구매자의 수 조회
SELECT * FROM TBL_BUYER;
SELECT * FROM TBL_ORDER;

SELECT COUNT(BUYER_AGE)
FROM TBL_BUYER TBU
JOIN TBL_ORDER TBO
ON TBU.ID = TBO.BUYER_ID
WHERE BUYER_AGE < 40 AND BUYER_AGE > 19;

-- 뉴발란스를 구매한 20대 구매자 이름 조회
SELECT BUYER_ID
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE PRODUCT_BRAND LIKE '%뉴발란스%';

SELECT BUYER_AGE
FROM TBL_BUYER 
WHERE ID IN (
	SELECT BUYER_ID
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	WHERE PRODUCT_BRAND LIKE '%뉴발란스%'
);

SELECT BUYER_NAME
FROM (
	SELECT *
	FROM TBL_BUYER 
	WHERE ID IN (
		SELECT BUYER_ID
		FROM TBL_ORDER TBO
		JOIN TBL_PRODUCT TBP
		ON TBO.PRODUCT_ID = TBP.ID
		WHERE PRODUCT_BRAND LIKE '%뉴발란스%'
	)
)
WHERE BUYER_AGE < 30 AND BUYER_AGE > 19;

--4) 여성의 나이대별 평균 지출 금액 조회
SELECT TBU.BUYER_AGE, ROUND(AVG(TBP.PRODUCT_PRICE))
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU 
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID
WHERE BUYER_GENDER = '여'
GROUP BY TBU.BUYER_AGE
ORDER BY ROUND(AVG(TBP.PRODUCT_PRICE)) DESC;

--5) 쇼핑몰의 총 판매 액수 조회
SELECT SUM(TBP.PRODUCT_PRICE)
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU 
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID;

--6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회
-- 매출이 적은 상품 -> 오더 + 상품
SELECT PRODUCT_ID
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY PRODUCT_PRICE, PRODUCT_ID
ORDER BY PRODUCT_PRICE * COUNT(PRODUCT_ID);

SELECT *
FROM (
	SELECT PRODUCT_ID
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	GROUP BY PRODUCT_PRICE, PRODUCT_ID
	ORDER BY PRODUCT_PRICE * COUNT(PRODUCT_ID)
)
WHERE ROWNUM <= 1;

SELECT BUYER_NAME, PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID
WHERE PRODUCT_ID = (
	SELECT *
	FROM (
	SELECT PRODUCT_ID
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	GROUP BY PRODUCT_PRICE, PRODUCT_ID
	ORDER BY PRODUCT_PRICE * COUNT(PRODUCT_ID)
	)
	WHERE ROWNUM <= 1
);

--7) 경기도에 거주한 사람이 구매한 상품과, 사용자 정보를 조회
--이름, 나이, 성별, 주소, 핸드폰
SELECT TBU.*, TBP.*
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU 
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID
WHERE BUYER_ADDRESS LIKE '%경기도%';

--8) 30대 남성이 가장 많이 구매한 상품의 이름 조회
SELECT TBO.PRODUCT_ID, COUNT(TBO.PRODUCT_ID), TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU 
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID
WHERE BUYER_AGE < 40 AND BUYER_AGE > 29
GROUP BY TBO.PRODUCT_ID, TBP.PRODUCT_NAME
ORDER BY COUNT(TBO.PRODUCT_ID) DESC;

SELECT PRODUCT_NAME
FROM (
	SELECT TBO.PRODUCT_ID, COUNT(TBO.PRODUCT_ID), TBP.PRODUCT_NAME
	FROM TBL_ORDER TBO
	JOIN TBL_BUYER TBU 
	ON TBO.BUYER_ID = TBU.ID
	JOIN TBL_PRODUCT TBP 
	ON TBO.PRODUCT_ID = TBP.ID
	WHERE BUYER_AGE < 40 AND BUYER_AGE > 29
	GROUP BY TBO.PRODUCT_ID, TBP.PRODUCT_NAME
	ORDER BY COUNT(TBO.PRODUCT_ID) DESC
)
WHERE ROWNUM <= 1;s

--9) 가장 적게 판매된 상품의 이름
SELECT PRODUCT_ID, COUNT(PRODUCT_ID), PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY COUNT(PRODUCT_ID);

SELECT PRODUCT_NAME
FROM (
	SELECT TBO.PRODUCT_ID, COUNT(TBO.PRODUCT_ID), TBP.PRODUCT_NAME
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP 
	ON TBO.PRODUCT_ID = TBP.ID
	GROUP BY TBO.PRODUCT_ID, TBP.PRODUCT_NAME
	ORDER BY COUNT(TBO.PRODUCT_ID)
)
WHERE ROWNUM <= 2;

--10) 평균 나이보다 많은 사용자들이 구매한 상품과 사용자의 정보 조회
SELECT AVG(BUYER_AGE)
FROM TBL_BUYER;

SELECT *
FROM TBL_BUYER 
WHERE BUYER_AGE > (
	SELECT AVG(BUYER_AGE)
	FROM TBL_BUYER
);

SELECT TBU.*, TBP.*
FROM TBL_ORDER TBO
JOIN (
	SELECT *
	FROM TBL_BUYER 
	WHERE BUYER_AGE > (
		SELECT AVG(BUYER_AGE)
		FROM TBL_BUYER
	)	
) TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID;

--11) 20대 여성이 구매한 상품 이름과 주문 건수 조회
SELECT *
FROM TBL_BUYER
WHERE BUYER_AGE >= 20 AND BUYER_AGE < 30;

SELECT *
FROM (
	SELECT *
	FROM TBL_BUYER
	WHERE BUYER_AGE >= 20 AND BUYER_AGE < 30
)
WHERE BUYER_GENDER LIKE '%여%';

SELECT TBP.PRODUCT_NAME, COUNT(TBO.PRODUCT_ID)
FROM TBL_ORDER TBO
JOIN (
	SELECT *
	FROM (
		SELECT *
		FROM TBL_BUYER
		WHERE BUYER_AGE >= 20 AND BUYER_AGE < 30
	)
	WHERE BUYER_GENDER LIKE '%여%'
) TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY TBP.PRODUCT_NAME, TBO.PRODUCT_ID;

--12) 가장 인기가 없는 상품 조회
SELECT TBP.ID
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY TBP.ID, TBO.PRODUCT_ID, TBP.PRODUCT_NAME
ORDER BY COUNT(TBO.PRODUCT_ID);

SELECT *
FROM(
	SELECT TBP.ID
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	GROUP BY TBP.ID, TBO.PRODUCT_ID, TBP.PRODUCT_NAME
	ORDER BY COUNT(TBO.PRODUCT_ID)
)
WHERE ROWNUM <= 2;

SELECT *
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT *
	FROM(
		SELECT TBP.ID
		FROM TBL_ORDER TBO
		JOIN TBL_PRODUCT TBP
		ON TBO.PRODUCT_ID = TBP.ID
		GROUP BY TBP.ID, TBO.PRODUCT_ID, TBP.PRODUCT_NAME
		ORDER BY COUNT(TBO.PRODUCT_ID)
	)
	WHERE ROWNUM <= 2
);