CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

SELECT * FROM TBL_PRODUCT;

SELECT * FROM TBL_PRODUCT;
SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 3;

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL
);

SELECT * FROM TBL_POST;

