CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER,
	MEMBER_ADDRESS VARCHAR2(255)
);

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, 'yhm12345', '1234', '윤한민', 20, '경기도 성남');

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, 'yhm12345', '1234', '최준서', 30, '경기도 성남');

DELETE FROM TBL_MEMBER WHERE ID = 7;